Add header and avatar image
AnastasiSo/Portfolio-Project pull request #1
Opened 2022-10-21 13:21 UTC by AnastasiiaSorina

[Notion](https://www.notion.so/Hero-add-Header-img-81290f99266843d58951bafc62a69eec).

2022-11-08 15:35 UTC, TaniaZaslon requested changes

2022-11-08 15:35 UTC, TaniaZaslon commented on src/_styles/_hero.scss
> +img {
Let's namespace this `img` with class, eg. "header-avatar" to avoid overwriting styles for all `img` on page.

2022-11-15 15:01 UTC, AnastasiiaSorina commented on src/_styles/_hero.scss
> +img {
✅ Done [020e0a4](https://github.com/AnastasiSo/Portfolio-Project/pull/1/commits/020e0a4b93deeb5e88cca7572f7b7b6675a15d28)

2022-11-15 15:39 UTC, TaniaZaslon approved these changes

2022-11-16 17:28 UTC, TaniaZaslon requested changes

2022-11-16 17:28 UTC, TaniaZaslon commented on src/components/hero/Hero.tsx
> +            <img className="header-avatar" src="./../img/foto.png" />
Let's add all static images to `/public/static/media` and path for image will be `/static/media/[past name of your file here]`.

2022-11-18 15:02 UTC, AnastasiiaSorina commented
Clouse. Because UX design is not relevant anymore.

2022-11-18 15:02 UTC, closed without merging