Testing
AnastasiSo/Portfolio-Project pull request #21
Opened 2023-03-06 11:08 UTC by AnastasiiaSorina

[Notion.](https://www.notion.so/MVP-22f60e2829a94ec8b274167ca6c43856?pvs=4)

- [ ] add id for Contacts.
- [ ] resume download> check file.

2023-04-25 15:02 UTC, TaniaZaslon requested changes

2023-04-25 15:02 UTC, TaniaZaslon commented on src/components/Menu.tsx
> +    { title: "Contacts", href: "#contacts" }, //
Let's remove `//`

2023-05-03 17:16 UTC, AnastasiiaSorina commented on src/components/Menu.tsx
> +    { title: "Contacts", href: "#contacts" }, //
- [ ] Done [939f821](https://github.com/AnastasiSo/Portfolio-Project/pull/21/commits/939f821e600e1426daa1c93ad5c8a29ca7d66ca2).

2023-05-05 09:10 UTC, TaniaZaslon approved these changes

2023-05-09 13:34 UTC, merged

2023-05-09 13:53 UTC, AnastasiiaSorina commented
Great job!!!