Import icon
AnastasiSo/Portfolio-Project pull request #8
Opened 2022-12-13 23:45 UTC by AnastasiiaSorina

[Notion](https://www.notion.so/Import-icon-b06a3b64baf24e328809e101b157db5e)

- [ ] create a Component icon
- [ ] import all Svg to Constants.

2022-12-14 14:42 UTC, TaniaZaslon requested changes

2022-12-14 14:42 UTC, TaniaZaslon commented on src/icon/Icon.tsx
> +import { FunctionComponent } from "react";
Let's move Icon component under `/src/component/` folder.

2022-12-14 17:08 UTC, AnastasiiaSorina commented on src/icon/Icon.tsx
> +import { FunctionComponent } from "react";
Okay. [a85b607](https://github.com/AnastasiSo/Portfolio-Project/pull/8/commits/a85b607d204fb51b0e5d6acbec372318d7ce57ba)

2022-12-15 06:10 UTC, TaniaZaslon commented on src/icon/Icon.tsx
> +import { FunctionComponent } from "react";
Whole folder "icon", with constant.ts too.

2022-12-23 18:36 UTC, AnastasiiaSorina commented on src/icon/Icon.tsx
> +import { FunctionComponent } from "react";
Done✅ [5c2386a](https://github.com/AnastasiSo/Portfolio-Project/pull/8/commits/5c2386a2b3276c74b7b6155dd10a7131f16c396c)

2022-12-23 21:22 UTC, TaniaZaslon approved these changes

2022-12-23 21:24 UTC, merged